version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DENABLE_BENCHMARKS=ON -DENABLE_EXAMPLES=ON -DBUILD_STATIC_LIB=ON -DENABLE_TESTS=ON .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln 

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\tests
  - ctest -C Release -VV
  - cd %APPVEYOR_BUILD_FOLDER%\benchmarks\Release
  - hawktracer_benchmarks

after_build:
  - msbuild PACKAGE.vcxproj

artifacts:
  - path: '*.exe'
  - path: client/Release/hawktracer-converter.exe

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/eab86d4da8e98dcfc646
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false